/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_single_by_sittichok_funjanchokcharoen_593410078.pkg4;

import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public class Different_Game2 extends javax.swing.JFrame {

    /**
     * Creates new form Different_Game2
     */
    public Different_Game2() {
        initComponents();
    }
    
    int score11 = 0;        //กำหนดตัวแปรค่า score (จำนวนจุดที่โดนหาเจอเเล้ว)
    int score22 = 3;        //จำนวนครั้งที่ใช้ได้ตอนกดผิด
    boolean winn = false;
    
    boolean lock11 = false;
    boolean lock22 = false;
    boolean lock33 = false;
    boolean lock44 = false;
    boolean lock55 = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gu1 = new javax.swing.JLabel();
        Gu2 = new javax.swing.JLabel();
        Gu3 = new javax.swing.JLabel();
        Gu4 = new javax.swing.JLabel();
        Gu5 = new javax.swing.JLabel();
        Gu6 = new javax.swing.JLabel();
        Gu7 = new javax.swing.JLabel();
        Gu8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PG1 = new javax.swing.JLabel();
        PG2 = new javax.swing.JLabel();
        main1 = new javax.swing.JLabel();
        sc = new javax.swing.JLabel();
        Point = new javax.swing.JLabel();
        F1 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        F5 = new javax.swing.JButton();
        F6 = new javax.swing.JButton();
        F7 = new javax.swing.JButton();
        F8 = new javax.swing.JButton();
        win = new javax.swing.JLabel();
        bg1 = new javax.swing.JButton();
        bg2 = new javax.swing.JButton();
        main3 = new javax.swing.JLabel();
        main4 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1325, 730));
        setMinimumSize(new java.awt.Dimension(1325, 730));
        getContentPane().setLayout(null);
        getContentPane().add(Gu1);
        Gu1.setBounds(30, 140, 140, 130);
        getContentPane().add(Gu2);
        Gu2.setBounds(680, 160, 140, 120);
        getContentPane().add(Gu3);
        Gu3.setBounds(390, 170, 140, 120);
        getContentPane().add(Gu4);
        Gu4.setBounds(1040, 180, 140, 120);
        getContentPane().add(Gu5);
        Gu5.setBounds(480, 210, 140, 120);
        getContentPane().add(Gu6);
        Gu6.setBounds(1130, 220, 140, 120);
        getContentPane().add(Gu7);
        Gu7.setBounds(510, 60, 140, 120);
        getContentPane().add(Gu8);
        Gu8.setBounds(1140, 60, 140, 120);

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 0, 30)); // NOI18N
        jLabel2.setText("  Different Game");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 215, 51);

        PG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_single_by_sittichok_funjanchokcharoen_593410078/pkg4/ProjectTerm 2/normal2.jpg"))); // NOI18N
        PG1.setText("jLabel1");
        getContentPane().add(PG1);
        PG1.setBounds(10, 57, 643, 480);

        PG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_single_by_sittichok_funjanchokcharoen_593410078/pkg4/ProjectTerm 2/normal.jpg"))); // NOI18N
        PG2.setText("jLabel1");
        getContentPane().add(PG2);
        PG2.setBounds(659, 57, 643, 480);

        main1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        main1.setText("Score : ");
        getContentPane().add(main1);
        main1.setBounds(20, 637, 83, 52);

        sc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sc.setText("0");
        getContentPane().add(sc);
        sc.setBounds(107, 636, 28, 52);

        Point.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Point.setText("3");
        getContentPane().add(Point);
        Point.setBounds(420, 640, 46, 52);

        F1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1ActionPerformed(evt);
            }
        });
        getContentPane().add(F1);
        F1.setBounds(70, 190, 70, 60);

        F2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F2ActionPerformed(evt);
            }
        });
        getContentPane().add(F2);
        F2.setBounds(720, 200, 70, 50);

        F3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F3ActionPerformed(evt);
            }
        });
        getContentPane().add(F3);
        F3.setBounds(460, 160, 30, 150);

        F4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F4ActionPerformed(evt);
            }
        });
        getContentPane().add(F4);
        F4.setBounds(1110, 150, 30, 150);

        F5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F5ActionPerformed(evt);
            }
        });
        getContentPane().add(F5);
        F5.setBounds(530, 230, 40, 40);

        F6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F6ActionPerformed(evt);
            }
        });
        getContentPane().add(F6);
        F6.setBounds(1180, 230, 40, 40);

        F7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F7ActionPerformed(evt);
            }
        });
        getContentPane().add(F7);
        F7.setBounds(560, 90, 40, 40);

        F8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F8ActionPerformed(evt);
            }
        });
        getContentPane().add(F8);
        F8.setBounds(1210, 90, 40, 40);

        win.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        getContentPane().add(win);
        win.setBounds(580, 550, 260, 100);

        bg1.setText("jButton1");
        bg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bg1ActionPerformed(evt);
            }
        });
        getContentPane().add(bg1);
        bg1.setBounds(10, 60, 640, 480);

        bg2.setText("jButton1");
        bg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bg2ActionPerformed(evt);
            }
        });
        getContentPane().add(bg2);
        bg2.setBounds(660, 60, 640, 480);

        main3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        main3.setText("/4");
        getContentPane().add(main3);
        main3.setBounds(141, 636, 40, 52);

        main4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        main4.setText("Piont :");
        getContentPane().add(main4);
        main4.setBounds(344, 636, 68, 52);

        back.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        back.setText("BACK");
        back.setMaximumSize(new java.awt.Dimension(50, 37));
        back.setMinimumSize(new java.awt.Dimension(50, 37));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(1134, 636, 168, 53);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void F1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ActionPerformed
        // TODO add your handling code here:
        
        if(winn==false)
        {
            if(lock11==false)
        {
            
            score11++;
            sc.setText(String.valueOf(score11));
            lock11=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu1.setIcon( icon1 );
                icon1.getImage().flush();
                Gu2.setIcon( icon1 );
           
        }
         if(score11 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
            
        }
        }
        
    }//GEN-LAST:event_F1ActionPerformed

    private void F2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F2ActionPerformed
        // TODO add your handling code here:
        
        if(winn==false)
        {
            if(lock11==false)
        {
            
            score11++;
            sc.setText(String.valueOf(score11));
            lock11=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu1.setIcon( icon1 );
                icon1.getImage().flush();
                Gu2.setIcon( icon1 );
           
        }
         if(score11 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
            
        }
        }
        
    }//GEN-LAST:event_F2ActionPerformed

    private void F3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F3ActionPerformed
        // TODO add your handling code here:
        
        if(winn==false)
        {
            if(lock22==false)
        {
            
            score11++;
            sc.setText(String.valueOf(score11));
            lock11=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu3.setIcon( icon1 );
                icon1.getImage().flush();
                Gu4.setIcon( icon1 );
           
        }
         if(score11 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
            
        }
        }
        
    }//GEN-LAST:event_F3ActionPerformed

    private void F4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F4ActionPerformed
        // TODO add your handling code here:
        
        if(winn==false)
        {
            if(lock22==false)
        {
            
            score11++;
            sc.setText(String.valueOf(score11));
            lock22=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu3.setIcon( icon1 );
                icon1.getImage().flush();
                Gu4.setIcon( icon1 );
           
        }
         if(score11 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
            
        }
        }
        
    }//GEN-LAST:event_F4ActionPerformed

    private void F5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F5ActionPerformed
        // TODO add your handling code here:
        
        if(winn==false)
        {
            if(lock33==false)
        {
            
            score11++;
            sc.setText(String.valueOf(score11));
            lock33=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu5.setIcon( icon1 );
                icon1.getImage().flush();
                Gu6.setIcon( icon1 );
           
        }
         if(score11 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
            
        }
        }
        
    }//GEN-LAST:event_F5ActionPerformed

    private void F6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F6ActionPerformed
        // TODO add your handling code here:
        
        if(winn==false)
        {
            if(lock33==false)
        {
            
            score11++;
            sc.setText(String.valueOf(score11));
            lock33=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu5.setIcon( icon1 );
                icon1.getImage().flush();
                Gu6.setIcon( icon1 );
           
        }
         if(score11 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
            
        }
        }
        
    }//GEN-LAST:event_F6ActionPerformed

    private void F7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F7ActionPerformed
        // TODO add your handling code here:
        
        if(winn==false)
        {
            if(lock44==false)
        {
            
            score11++;
            sc.setText(String.valueOf(score11));
            lock44=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu7.setIcon( icon1 );
                icon1.getImage().flush();
                Gu8.setIcon( icon1 );
           
        }
         if(score11 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
            
        }
        }
        
    }//GEN-LAST:event_F7ActionPerformed

    private void F8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F8ActionPerformed
        // TODO add your handling code here:
        
        if(winn==false)
        {
            if(lock44==false)
        {
            
            score11++;
            sc.setText(String.valueOf(score11));
            lock44=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu7.setIcon( icon1 );
                icon1.getImage().flush();
                Gu8.setIcon( icon1 );
           
        }
         if(score11 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
            
        }
        }
        
    }//GEN-LAST:event_F8ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
        Different_Game run = new Different_Game();
        run.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_backActionPerformed

    private void bg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bg1ActionPerformed
        // TODO add your handling code here:
        
        if(winn==false)
        {
        if(score22>0){
            score22--;
        Point.setText(String.valueOf(score22)
        
        
        );
        }
        if(score22 == 0 )
        {
            win.setText(String.valueOf("You lose"));
            boolean lock11 = true;
            boolean lock22 = true;
            boolean lock33 = true;
            boolean lock44 = true;
            boolean lock55 = true;
            winn=true;
            
        }
        }
        
    }//GEN-LAST:event_bg1ActionPerformed

    private void bg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bg2ActionPerformed
        // TODO add your handling code here:
        
        if(winn==false)
        {
        if(score22>0){
            score22--;
        Point.setText(String.valueOf(score22)
        
        
        );
        }
        if(score22 == 0 )
        {
            win.setText(String.valueOf("You lose"));
            boolean lock11 = true;
            boolean lock22 = true;
            boolean lock33 = true;
            boolean lock44 = true;
            boolean lock55 = true;
            winn=true;
            
        }
        }
        
    }//GEN-LAST:event_bg2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Different_Game2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Different_Game2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Different_Game2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Different_Game2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Different_Game2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton F1;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton F4;
    private javax.swing.JButton F5;
    private javax.swing.JButton F6;
    private javax.swing.JButton F7;
    private javax.swing.JButton F8;
    private javax.swing.JLabel Gu1;
    private javax.swing.JLabel Gu2;
    private javax.swing.JLabel Gu3;
    private javax.swing.JLabel Gu4;
    private javax.swing.JLabel Gu5;
    private javax.swing.JLabel Gu6;
    private javax.swing.JLabel Gu7;
    private javax.swing.JLabel Gu8;
    private javax.swing.JLabel PG1;
    private javax.swing.JLabel PG2;
    private javax.swing.JLabel Point;
    private javax.swing.JButton back;
    private javax.swing.JButton bg1;
    private javax.swing.JButton bg2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel main1;
    private javax.swing.JLabel main3;
    private javax.swing.JLabel main4;
    private javax.swing.JLabel sc;
    private javax.swing.JLabel win;
    // End of variables declaration//GEN-END:variables
}
