/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_single_by_sittichok_funjanchokcharoen_593410078.pkg4;

import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public class Different_Game extends javax.swing.JFrame {

    /**
     * Creates new form Different_Game
     */
    public Different_Game() {
        initComponents();
    }
    int score1 = 0;        //กำหนดตัวแปรค่า score (จำนวนจุดที่โดนหาเจอเเล้ว)
    int score2 = 3;        //จำนวน
    boolean winn = false;
    
    boolean lock1 = false;
    boolean lock2 = false;
    boolean lock3 = false;
    boolean lock4 = false;
    boolean lock5 = false;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Head = new javax.swing.JLabel();
        Gu1 = new javax.swing.JLabel();
        Gu2 = new javax.swing.JLabel();
        Gu3 = new javax.swing.JLabel();
        Gu4 = new javax.swing.JLabel();
        Gu5 = new javax.swing.JLabel();
        Gu6 = new javax.swing.JLabel();
        Gu7 = new javax.swing.JLabel();
        Gu8 = new javax.swing.JLabel();
        PG1 = new javax.swing.JLabel();
        PG2 = new javax.swing.JLabel();
        F1 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        F5 = new javax.swing.JButton();
        F6 = new javax.swing.JButton();
        F7 = new javax.swing.JButton();
        F8 = new javax.swing.JButton();
        sc = new javax.swing.JLabel();
        sc1 = new javax.swing.JLabel();
        sc2 = new javax.swing.JLabel();
        sc3 = new javax.swing.JLabel();
        sc4 = new javax.swing.JLabel();
        bg1 = new javax.swing.JButton();
        bg2 = new javax.swing.JButton();
        win = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1102, 861));
        setMinimumSize(new java.awt.Dimension(1102, 861));
        getContentPane().setLayout(null);

        Head.setFont(new java.awt.Font("Tekton Pro", 0, 30)); // NOI18N
        Head.setText("  Different Game");
        getContentPane().add(Head);
        Head.setBounds(0, 0, 215, 51);
        getContentPane().add(Gu1);
        Gu1.setBounds(420, 220, 140, 120);
        getContentPane().add(Gu2);
        Gu2.setBounds(410, 610, 140, 120);
        getContentPane().add(Gu3);
        Gu3.setBounds(150, 120, 140, 130);
        getContentPane().add(Gu4);
        Gu4.setBounds(140, 510, 150, 130);
        getContentPane().add(Gu5);
        Gu5.setBounds(60, 290, 150, 130);
        getContentPane().add(Gu6);
        Gu6.setBounds(60, 680, 160, 130);
        getContentPane().add(Gu7);
        Gu7.setBounds(540, 40, 150, 130);
        getContentPane().add(Gu8);
        Gu8.setBounds(540, 440, 150, 130);

        PG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_single_by_sittichok_funjanchokcharoen_593410078/pkg4/ProjectTerm 2/easy.jpg"))); // NOI18N
        PG1.setText("jLabel2");
        getContentPane().add(PG1);
        PG1.setBounds(10, 40, 679, 383);

        PG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_single_by_sittichok_funjanchokcharoen_593410078/pkg4/ProjectTerm 2/easy2.jpg"))); // NOI18N
        PG2.setText("jLabel2");
        getContentPane().add(PG2);
        PG2.setBounds(10, 430, 679, 383);

        F1.setText("F1");
        F1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1ActionPerformed(evt);
            }
        });
        getContentPane().add(F1);
        F1.setBounds(450, 240, 90, 80);

        F2.setText("F2");
        F2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F2ActionPerformed(evt);
            }
        });
        getContentPane().add(F2);
        F2.setBounds(450, 630, 80, 80);

        F3.setText("F3");
        F3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F3ActionPerformed(evt);
            }
        });
        getContentPane().add(F3);
        F3.setBounds(180, 150, 60, 60);

        F4.setText("F4");
        F4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F4ActionPerformed(evt);
            }
        });
        getContentPane().add(F4);
        F4.setBounds(180, 550, 60, 60);

        F5.setText("F5");
        F5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F5ActionPerformed(evt);
            }
        });
        getContentPane().add(F5);
        F5.setBounds(60, 350, 180, 50);

        F6.setText("F6");
        F6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F6ActionPerformed(evt);
            }
        });
        getContentPane().add(F6);
        F6.setBounds(60, 740, 180, 50);

        F7.setText("F7");
        F7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F7ActionPerformed(evt);
            }
        });
        getContentPane().add(F7);
        F7.setBounds(540, 60, 150, 130);

        F8.setText("F8");
        F8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F8ActionPerformed(evt);
            }
        });
        getContentPane().add(F8);
        F8.setBounds(540, 450, 150, 140);

        sc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(sc);
        sc.setBounds(840, 40, 20, 40);

        sc1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sc1.setText("/4");
        getContentPane().add(sc1);
        sc1.setBounds(860, 40, 30, 40);

        sc2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sc2.setText("Score :");
        getContentPane().add(sc2);
        sc2.setBounds(750, 40, 80, 40);

        sc3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sc3.setText(" Piont :");
        getContentPane().add(sc3);
        sc3.setBounds(750, 100, 90, 40);

        sc4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sc4.setText("3");
        getContentPane().add(sc4);
        sc4.setBounds(840, 100, 30, 40);

        bg1.setText("Back");
        bg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bg1ActionPerformed(evt);
            }
        });
        getContentPane().add(bg1);
        bg1.setBounds(10, 40, 680, 380);

        bg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bg2ActionPerformed(evt);
            }
        });
        getContentPane().add(bg2);
        bg2.setBounds(10, 430, 680, 380);

        win.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        getContentPane().add(win);
        win.setBounds(740, 170, 300, 60);

        back.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(780, 760, 150, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void F1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ActionPerformed
        
        if(winn==false)
        {
            if(lock1==false)
        {
            
            score1++;
            sc.setText(String.valueOf(score1));
            lock1=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu1.setIcon( icon1 );
                icon1.getImage().flush();
                Gu2.setIcon( icon1 );
           
        }
         if(score1 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
            
        }
        }
        
    }//GEN-LAST:event_F1ActionPerformed

    private void F6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F6ActionPerformed
         if(winn==false)
        {
       if(lock3==false)
        {
            
            score1++;
            sc.setText(String.valueOf(score1));
            lock3=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu5.setIcon( icon1 );
                icon1.getImage().flush();
                Gu6.setIcon( icon1 );
        }
       if(score1 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
        }
        }
    }//GEN-LAST:event_F6ActionPerformed
        
    private void F2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F2ActionPerformed
         if(winn==false)
        {
        if(lock1==false)
        {
            
            score1++;
            sc.setText(String.valueOf(score1));
            lock1=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu1.setIcon( icon1 );
                icon1.getImage().flush();
                Gu2.setIcon( icon1 );           
        }
        if(score1 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
        }
        }
    }//GEN-LAST:event_F2ActionPerformed

    private void F3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F3ActionPerformed
         if(winn==false)
        {
        if(lock2==false)
        {
            
            score1++;
            sc.setText(String.valueOf(score1));
            lock2=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu3.setIcon( icon1 );
                icon1.getImage().flush();
                Gu4.setIcon( icon1 );
        }
        if(score1 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
        }
        }
    }//GEN-LAST:event_F3ActionPerformed

    private void F8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F8ActionPerformed
         if(winn==false)
        {
        if(lock4==false)
        {
            
            score1++;
            sc.setText(String.valueOf(score1));
            lock4=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu7.setIcon( icon1 );
                icon1.getImage().flush();
                Gu8.setIcon( icon1 );
        }
        if(score1 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
        }
        }
    }//GEN-LAST:event_F8ActionPerformed

    private void F5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F5ActionPerformed
         if(winn==false)
        {
        if(lock3==false)
        {
            
            score1++;
            sc.setText(String.valueOf(score1));
            lock3=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu5.setIcon( icon1 );
                icon1.getImage().flush();
                Gu6.setIcon( icon1 );
        }
        if(score1 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
        }
        }
    }//GEN-LAST:event_F5ActionPerformed

    private void F7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F7ActionPerformed
         if(winn==false)
        {
        if(lock4==false)
        {
            
            score1++;
            sc.setText(String.valueOf(score1));
            lock4=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu7.setIcon( icon1 );
                icon1.getImage().flush();
                Gu8.setIcon( icon1 );
        }
        if(score1 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
        }
        }
    }//GEN-LAST:event_F7ActionPerformed

    private void F4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F4ActionPerformed
        if(winn==false)
        {
        if(lock2==false)
        {
            
            score1++;
            sc.setText(String.valueOf(score1));
            lock2=true;
            ImageIcon icon1 = new ImageIcon(getClass().getResource("ProjectTerm 2/CC1.png"));
                icon1.getImage().flush();
                Gu3.setIcon( icon1 );
                icon1.getImage().flush();
                Gu4.setIcon( icon1 );
        }
        if(score1 == 4 )
        {
            win.setText(String.valueOf("You win"));
            winn = true;
        }
        }
    }//GEN-LAST:event_F4ActionPerformed

    private void bg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bg1ActionPerformed
        // TODO add your handling code here:
        if(winn==false)
        {
        if(score2>0){
            score2--;
        sc4.setText(String.valueOf(score2)
        
        
        );
        }
        if(score2 == 0 )
        {
            win.setText(String.valueOf("You lose"));
            boolean lock1 = true;
            boolean lock2 = true;
            boolean lock3 = true;
            boolean lock4 = true;
            boolean lock5 = true;
            winn=true;
            
        }
        }
    
    }//GEN-LAST:event_bg1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
        memu run = new memu();
        run.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void bg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bg2ActionPerformed
        // TODO add your handling code here:
        
        if(winn==false)
        {
        if(score2>0){
            score2--;
        sc4.setText(String.valueOf(score2)
        
        
        );
        }
        if(score2 == 0 )
        {
            win.setText(String.valueOf("You lose"));
            boolean lock1 = true;
            boolean lock2 = true;
            boolean lock3 = true;
            boolean lock4 = true;
            boolean lock5 = true;
            winn=true;
            
        }
        }
    
    }//GEN-LAST:event_bg2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Different_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Different_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Different_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Different_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Different_Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton F1;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton F4;
    private javax.swing.JButton F5;
    private javax.swing.JButton F6;
    private javax.swing.JButton F7;
    private javax.swing.JButton F8;
    private javax.swing.JLabel Gu1;
    private javax.swing.JLabel Gu2;
    private javax.swing.JLabel Gu3;
    private javax.swing.JLabel Gu4;
    private javax.swing.JLabel Gu5;
    private javax.swing.JLabel Gu6;
    private javax.swing.JLabel Gu7;
    private javax.swing.JLabel Gu8;
    private javax.swing.JLabel Head;
    private javax.swing.JLabel PG1;
    private javax.swing.JLabel PG2;
    private javax.swing.JButton back;
    private javax.swing.JButton bg1;
    private javax.swing.JButton bg2;
    private javax.swing.JLabel sc;
    private javax.swing.JLabel sc1;
    private javax.swing.JLabel sc2;
    private javax.swing.JLabel sc3;
    private javax.swing.JLabel sc4;
    private javax.swing.JLabel win;
    // End of variables declaration//GEN-END:variables
}
